/**
 * Seed public recipes for offline community browse (until Supabase public list is wired).
 * Originally written for The Good Pantry — not scraped.
 */

import type { RecipeDetail } from '../../db/types';

const now = '2026-07-20T12:00:00.000Z';

export const DEMO_PUBLIC_RECIPES: RecipeDetail[] = [
  {
    id: 'pub_lemon_herb_chicken',
    householdId: null,
    title: 'Lemon Herb Skillet Chicken',
    servings: 4,
    prepMin: 15,
    cookMin: 25,
    visibility: 'public',
    tags: ['chicken', 'weeknight', 'skillet'],
    imageUrl: null,
    updatedAt: now,
    yieldNote: null,
    authorId: 'author_alex',
    forkedFrom: null,
    createdAt: '2026-06-01T10:00:00.000Z',
    ingredients: [
      {
        id: 'l1',
        sortOrder: 0,
        rawText: '4 chicken thighs',
        ingredientId: 'chicken-thigh',
        formId: 'chicken-thigh-raw',
        qty: 4,
        unit: 'each',
        unknownAllergens: false,
      },
      {
        id: 'l2',
        sortOrder: 1,
        rawText: '2 tbsp olive oil',
        ingredientId: 'olive-oil',
        formId: 'olive-oil-liquid',
        qty: 2,
        unit: 'tbsp',
        unknownAllergens: false,
      },
      {
        id: 'l3',
        sortOrder: 2,
        rawText: '1 lemon, juiced',
        qty: 1,
        unit: 'each',
        unknownAllergens: true,
      },
      {
        id: 'l4',
        sortOrder: 3,
        rawText: '2 cloves garlic',
        ingredientId: 'garlic',
        formId: 'garlic-clove',
        qty: 2,
        unit: 'clove',
        unknownAllergens: false,
      },
    ],
    steps: [
      {
        id: 's1',
        sortOrder: 0,
        text: 'Pat chicken dry and season with salt and pepper.',
      },
      {
        id: 's2',
        sortOrder: 1,
        text: 'Sear in olive oil until golden, about 6 minutes per side.',
      },
      {
        id: 's3',
        sortOrder: 2,
        text: 'Add garlic and lemon juice; finish on low until cooked through.',
      },
    ],
  },
  {
    id: 'pub_tomato_basil_pasta',
    householdId: null,
    title: 'Quick Tomato Basil Pasta',
    servings: 2,
    prepMin: 10,
    cookMin: 15,
    visibility: 'public',
    tags: ['pasta', 'vegetarian', 'quick'],
    imageUrl: null,
    updatedAt: now,
    yieldNote: null,
    authorId: 'author_sam',
    forkedFrom: null,
    createdAt: '2026-06-15T10:00:00.000Z',
    ingredients: [
      {
        id: 'p1',
        sortOrder: 0,
        rawText: '200 g pasta',
        ingredientId: 'pasta',
        formId: 'pasta-dry',
        qty: 200,
        unit: 'g',
        unknownAllergens: false,
      },
      {
        id: 'p2',
        sortOrder: 1,
        rawText: '1 can crushed tomatoes',
        qty: 1,
        unit: 'can',
        unknownAllergens: true,
      },
      {
        id: 'p3',
        sortOrder: 2,
        rawText: 'handful fresh basil',
        nonQuantified: true,
        qty: null,
        unit: null,
        unknownAllergens: true,
      },
    ],
    steps: [
      {
        id: 'ps1',
        sortOrder: 0,
        text: 'Boil pasta in salted water until al dente.',
      },
      {
        id: 'ps2',
        sortOrder: 1,
        text: 'Warm tomatoes with a splash of pasta water; toss with pasta and basil.',
      },
    ],
  },
  {
    id: 'pub_overnight_oats',
    householdId: null,
    title: 'Maple Overnight Oats',
    servings: 1,
    prepMin: 5,
    cookMin: 0,
    visibility: 'public',
    tags: ['breakfast', 'make-ahead', 'oats'],
    imageUrl: null,
    updatedAt: now,
    yieldNote: null,
    authorId: 'author_alex',
    forkedFrom: null,
    createdAt: '2026-07-01T10:00:00.000Z',
    ingredients: [
      {
        id: 'o1',
        sortOrder: 0,
        rawText: '1/2 cup rolled oats',
        ingredientId: 'oats',
        formId: 'oats-rolled',
        qty: 0.5,
        unit: 'cup',
        unknownAllergens: false,
      },
      {
        id: 'o2',
        sortOrder: 1,
        rawText: '1/2 cup milk',
        ingredientId: 'milk',
        formId: 'milk-liquid',
        qty: 0.5,
        unit: 'cup',
        unknownAllergens: false,
      },
      {
        id: 'o3',
        sortOrder: 2,
        rawText: '1 tbsp maple syrup',
        qty: 1,
        unit: 'tbsp',
        unknownAllergens: true,
      },
    ],
    steps: [
      {
        id: 'os1',
        sortOrder: 0,
        text: 'Stir oats, milk, and maple in a jar. Chill overnight.',
      },
    ],
  },
];
